# based on https://docs.docker.com/compose/rails/
version: '3'
services:
  pg:
    restart: unless-stopped
    container_name: bpldc_authority_pg
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bostonlibrary/bpldc_authority_api:dev-latest
    container_name: bpldc_authority_api
    env_file: .env
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=pg
      - BPLDC_REDIS_CACHE_URL=redis://cache:6379/0
    volumes:
      - .:/bpldc_authority_api-app
    ports:
      - "3001:3000"
    depends_on:
      - pg
      - cache
  cache:
    restart: unless-stopped
    #mem_reservation: 32m
    image: redis:latest
    container_name: bpldc_authority_cache
    privileged: true
    command: >
      bash -c "echo 1 > /proc/sys/vm/overcommit_memory &&
      redis-server --databases 1 --maxmemory 16mb --maxmemory-policy allkeys-lfu"
    ulimits:
      nproc: 16384
    sysctls:
      net.core.somaxconn: 1024

volumes:
  pg_data:
