# based on https://docs.docker.com/compose/rails/
version: '3'
services:
  pg:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  bpldc_authority_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=pg
    volumes:
      - .:/bpldc_authority_api-app
    ports:
      - "3001:3000"
    depends_on:
      - pg

volumes:
  pg_data:
