default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

development:
  <<: *default
  database: bpldc_authority_api_development

test:
  <<: *default
  database: bpldc_authority_api_test

staging:
  <<: *default
  database: bpldc_authority_api_staging
  username: <%= ENV.fetch('BPLDC_AUTHORITY_API_DATABASE_USERNAME') { Rails.application.credentials.dig(:postgres, :user) } %>
  password: <%= ENV.fetch('BPLDC_AUTHORITY_API_DATABASE_PASSWORD') { Rails.application.credentials.dig(:postgres, :password) } %>

production:
  <<: *default
  database: bpldc_authority_api_production
  username: <%= ENV.fetch('BPLDC_AUTHORITY_API_DATABASE_USERNAME') { Rails.application.credentials.dig(:postgres, :user) } %>
  password: <%= ENV.fetch('BPLDC_AUTHORITY_API_DATABASE_PASSWORD') { Rails.application.credentials.dig(:postgres, :password) } %>
  host: <%= ENV.fetch('BPLDC_AUTHORITY_API_HOST') { Rails.application.credentials.dig(:postgres, :host) } %>
  port: <%= ENV.fetch('BPLDC_AUTHORITY_API_PORT') { Rails.application.credentials.dig(:postgres, :port) } %>
