default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: bpldc_authority_api_development

test:
  <<: *default
  database: bpldc_authority_api_test

production:
  <<: *default
  database: bpldc_authority_api_production
  username: <%= ENV['BPLDC_AUTHORITY_API_DATABASE_USERNAME'] %>
  password: <%= ENV['BPLDC_AUTHORITY_API_DATABASE_PASSWORD'] %>
